// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment.proto

package ir.asparsa.common.net.dto;

public final class CommentProto {
  private CommentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ir.asparsa.common.net.dto.Comments)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    java.util.List<ir.asparsa.common.net.dto.CommentProto.Comment> 
        getCommentList();
    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    ir.asparsa.common.net.dto.CommentProto.Comment getComment(int index);
    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    int getCommentCount();
    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    java.util.List<? extends ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder> 
        getCommentOrBuilderList();
    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder getCommentOrBuilder(
        int index);

    /**
     * <code>int64 totalElements = 2;</code>
     */
    long getTotalElements();
  }
  /**
   * Protobuf type {@code ir.asparsa.common.net.dto.Comments}
   */
  public  static final class Comments extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ir.asparsa.common.net.dto.Comments)
      CommentsOrBuilder {
    // Use Comments.newBuilder() to construct.
    private Comments(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Comments() {
      comment_ = java.util.Collections.emptyList();
      totalElements_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Comments(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                comment_ = new java.util.ArrayList<ir.asparsa.common.net.dto.CommentProto.Comment>();
                mutable_bitField0_ |= 0x00000001;
              }
              comment_.add(
                  input.readMessage(ir.asparsa.common.net.dto.CommentProto.Comment.parser(), extensionRegistry));
              break;
            }
            case 16: {

              totalElements_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          comment_ = java.util.Collections.unmodifiableList(comment_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comments_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.asparsa.common.net.dto.CommentProto.Comments.class, ir.asparsa.common.net.dto.CommentProto.Comments.Builder.class);
    }

    private int bitField0_;
    public static final int COMMENT_FIELD_NUMBER = 1;
    private java.util.List<ir.asparsa.common.net.dto.CommentProto.Comment> comment_;
    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    public java.util.List<ir.asparsa.common.net.dto.CommentProto.Comment> getCommentList() {
      return comment_;
    }
    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    public java.util.List<? extends ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder> 
        getCommentOrBuilderList() {
      return comment_;
    }
    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    public int getCommentCount() {
      return comment_.size();
    }
    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    public ir.asparsa.common.net.dto.CommentProto.Comment getComment(int index) {
      return comment_.get(index);
    }
    /**
     * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
     */
    public ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder getCommentOrBuilder(
        int index) {
      return comment_.get(index);
    }

    public static final int TOTALELEMENTS_FIELD_NUMBER = 2;
    private long totalElements_;
    /**
     * <code>int64 totalElements = 2;</code>
     */
    public long getTotalElements() {
      return totalElements_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < comment_.size(); i++) {
        output.writeMessage(1, comment_.get(i));
      }
      if (totalElements_ != 0L) {
        output.writeInt64(2, totalElements_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < comment_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, comment_.get(i));
      }
      if (totalElements_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, totalElements_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ir.asparsa.common.net.dto.CommentProto.Comments)) {
        return super.equals(obj);
      }
      ir.asparsa.common.net.dto.CommentProto.Comments other = (ir.asparsa.common.net.dto.CommentProto.Comments) obj;

      boolean result = true;
      result = result && getCommentList()
          .equals(other.getCommentList());
      result = result && (getTotalElements()
          == other.getTotalElements());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCommentCount() > 0) {
        hash = (37 * hash) + COMMENT_FIELD_NUMBER;
        hash = (53 * hash) + getCommentList().hashCode();
      }
      hash = (37 * hash) + TOTALELEMENTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalElements());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ir.asparsa.common.net.dto.CommentProto.Comments parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comments parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comments parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comments parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comments parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comments parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comments parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comments parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comments parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comments parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ir.asparsa.common.net.dto.CommentProto.Comments prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ir.asparsa.common.net.dto.Comments}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ir.asparsa.common.net.dto.Comments)
        ir.asparsa.common.net.dto.CommentProto.CommentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comments_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comments_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ir.asparsa.common.net.dto.CommentProto.Comments.class, ir.asparsa.common.net.dto.CommentProto.Comments.Builder.class);
      }

      // Construct using ir.asparsa.common.net.dto.CommentProto.Comments.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCommentFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (commentBuilder_ == null) {
          comment_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          commentBuilder_.clear();
        }
        totalElements_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comments_descriptor;
      }

      public ir.asparsa.common.net.dto.CommentProto.Comments getDefaultInstanceForType() {
        return ir.asparsa.common.net.dto.CommentProto.Comments.getDefaultInstance();
      }

      public ir.asparsa.common.net.dto.CommentProto.Comments build() {
        ir.asparsa.common.net.dto.CommentProto.Comments result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ir.asparsa.common.net.dto.CommentProto.Comments buildPartial() {
        ir.asparsa.common.net.dto.CommentProto.Comments result = new ir.asparsa.common.net.dto.CommentProto.Comments(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (commentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            comment_ = java.util.Collections.unmodifiableList(comment_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.comment_ = comment_;
        } else {
          result.comment_ = commentBuilder_.build();
        }
        result.totalElements_ = totalElements_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ir.asparsa.common.net.dto.CommentProto.Comments) {
          return mergeFrom((ir.asparsa.common.net.dto.CommentProto.Comments)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ir.asparsa.common.net.dto.CommentProto.Comments other) {
        if (other == ir.asparsa.common.net.dto.CommentProto.Comments.getDefaultInstance()) return this;
        if (commentBuilder_ == null) {
          if (!other.comment_.isEmpty()) {
            if (comment_.isEmpty()) {
              comment_ = other.comment_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCommentIsMutable();
              comment_.addAll(other.comment_);
            }
            onChanged();
          }
        } else {
          if (!other.comment_.isEmpty()) {
            if (commentBuilder_.isEmpty()) {
              commentBuilder_.dispose();
              commentBuilder_ = null;
              comment_ = other.comment_;
              bitField0_ = (bitField0_ & ~0x00000001);
              commentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCommentFieldBuilder() : null;
            } else {
              commentBuilder_.addAllMessages(other.comment_);
            }
          }
        }
        if (other.getTotalElements() != 0L) {
          setTotalElements(other.getTotalElements());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ir.asparsa.common.net.dto.CommentProto.Comments parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ir.asparsa.common.net.dto.CommentProto.Comments) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ir.asparsa.common.net.dto.CommentProto.Comment> comment_ =
        java.util.Collections.emptyList();
      private void ensureCommentIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          comment_ = new java.util.ArrayList<ir.asparsa.common.net.dto.CommentProto.Comment>(comment_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ir.asparsa.common.net.dto.CommentProto.Comment, ir.asparsa.common.net.dto.CommentProto.Comment.Builder, ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder> commentBuilder_;

      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public java.util.List<ir.asparsa.common.net.dto.CommentProto.Comment> getCommentList() {
        if (commentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(comment_);
        } else {
          return commentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public int getCommentCount() {
        if (commentBuilder_ == null) {
          return comment_.size();
        } else {
          return commentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public ir.asparsa.common.net.dto.CommentProto.Comment getComment(int index) {
        if (commentBuilder_ == null) {
          return comment_.get(index);
        } else {
          return commentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public Builder setComment(
          int index, ir.asparsa.common.net.dto.CommentProto.Comment value) {
        if (commentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommentIsMutable();
          comment_.set(index, value);
          onChanged();
        } else {
          commentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public Builder setComment(
          int index, ir.asparsa.common.net.dto.CommentProto.Comment.Builder builderForValue) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          comment_.set(index, builderForValue.build());
          onChanged();
        } else {
          commentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public Builder addComment(ir.asparsa.common.net.dto.CommentProto.Comment value) {
        if (commentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommentIsMutable();
          comment_.add(value);
          onChanged();
        } else {
          commentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public Builder addComment(
          int index, ir.asparsa.common.net.dto.CommentProto.Comment value) {
        if (commentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommentIsMutable();
          comment_.add(index, value);
          onChanged();
        } else {
          commentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public Builder addComment(
          ir.asparsa.common.net.dto.CommentProto.Comment.Builder builderForValue) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          comment_.add(builderForValue.build());
          onChanged();
        } else {
          commentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public Builder addComment(
          int index, ir.asparsa.common.net.dto.CommentProto.Comment.Builder builderForValue) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          comment_.add(index, builderForValue.build());
          onChanged();
        } else {
          commentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public Builder addAllComment(
          java.lang.Iterable<? extends ir.asparsa.common.net.dto.CommentProto.Comment> values) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, comment_);
          onChanged();
        } else {
          commentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public Builder clearComment() {
        if (commentBuilder_ == null) {
          comment_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          commentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public Builder removeComment(int index) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          comment_.remove(index);
          onChanged();
        } else {
          commentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public ir.asparsa.common.net.dto.CommentProto.Comment.Builder getCommentBuilder(
          int index) {
        return getCommentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder getCommentOrBuilder(
          int index) {
        if (commentBuilder_ == null) {
          return comment_.get(index);  } else {
          return commentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public java.util.List<? extends ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder> 
           getCommentOrBuilderList() {
        if (commentBuilder_ != null) {
          return commentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(comment_);
        }
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public ir.asparsa.common.net.dto.CommentProto.Comment.Builder addCommentBuilder() {
        return getCommentFieldBuilder().addBuilder(
            ir.asparsa.common.net.dto.CommentProto.Comment.getDefaultInstance());
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public ir.asparsa.common.net.dto.CommentProto.Comment.Builder addCommentBuilder(
          int index) {
        return getCommentFieldBuilder().addBuilder(
            index, ir.asparsa.common.net.dto.CommentProto.Comment.getDefaultInstance());
      }
      /**
       * <code>repeated .ir.asparsa.common.net.dto.Comment comment = 1;</code>
       */
      public java.util.List<ir.asparsa.common.net.dto.CommentProto.Comment.Builder> 
           getCommentBuilderList() {
        return getCommentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ir.asparsa.common.net.dto.CommentProto.Comment, ir.asparsa.common.net.dto.CommentProto.Comment.Builder, ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder> 
          getCommentFieldBuilder() {
        if (commentBuilder_ == null) {
          commentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ir.asparsa.common.net.dto.CommentProto.Comment, ir.asparsa.common.net.dto.CommentProto.Comment.Builder, ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder>(
                  comment_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          comment_ = null;
        }
        return commentBuilder_;
      }

      private long totalElements_ ;
      /**
       * <code>int64 totalElements = 2;</code>
       */
      public long getTotalElements() {
        return totalElements_;
      }
      /**
       * <code>int64 totalElements = 2;</code>
       */
      public Builder setTotalElements(long value) {
        
        totalElements_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 totalElements = 2;</code>
       */
      public Builder clearTotalElements() {
        
        totalElements_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ir.asparsa.common.net.dto.Comments)
    }

    // @@protoc_insertion_point(class_scope:ir.asparsa.common.net.dto.Comments)
    private static final ir.asparsa.common.net.dto.CommentProto.Comments DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ir.asparsa.common.net.dto.CommentProto.Comments();
    }

    public static ir.asparsa.common.net.dto.CommentProto.Comments getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Comments>
        PARSER = new com.google.protobuf.AbstractParser<Comments>() {
      public Comments parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Comments(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Comments> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Comments> getParserForType() {
      return PARSER;
    }

    public ir.asparsa.common.net.dto.CommentProto.Comments getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ir.asparsa.common.net.dto.Comment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string description = 1;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 1;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>int64 hash_code = 2;</code>
     */
    long getHashCode();

    /**
     * <code>string creator = 3;</code>
     */
    java.lang.String getCreator();
    /**
     * <code>string creator = 3;</code>
     */
    com.google.protobuf.ByteString
        getCreatorBytes();

    /**
     * <code>int64 created = 4;</code>
     */
    long getCreated();

    /**
     * <code>int64 store_hash_code = 5;</code>
     */
    long getStoreHashCode();

    /**
     * <code>int64 rate = 6;</code>
     */
    long getRate();

    /**
     * <code>bool like = 7;</code>
     */
    boolean getLike();
  }
  /**
   * Protobuf type {@code ir.asparsa.common.net.dto.Comment}
   */
  public  static final class Comment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ir.asparsa.common.net.dto.Comment)
      CommentOrBuilder {
    // Use Comment.newBuilder() to construct.
    private Comment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Comment() {
      description_ = "";
      hashCode_ = 0L;
      creator_ = "";
      created_ = 0L;
      storeHashCode_ = 0L;
      rate_ = 0L;
      like_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Comment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 16: {

              hashCode_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              creator_ = s;
              break;
            }
            case 32: {

              created_ = input.readInt64();
              break;
            }
            case 40: {

              storeHashCode_ = input.readInt64();
              break;
            }
            case 48: {

              rate_ = input.readInt64();
              break;
            }
            case 56: {

              like_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.asparsa.common.net.dto.CommentProto.Comment.class, ir.asparsa.common.net.dto.CommentProto.Comment.Builder.class);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 1;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASH_CODE_FIELD_NUMBER = 2;
    private long hashCode_;
    /**
     * <code>int64 hash_code = 2;</code>
     */
    public long getHashCode() {
      return hashCode_;
    }

    public static final int CREATOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object creator_;
    /**
     * <code>string creator = 3;</code>
     */
    public java.lang.String getCreator() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      }
    }
    /**
     * <code>string creator = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_FIELD_NUMBER = 4;
    private long created_;
    /**
     * <code>int64 created = 4;</code>
     */
    public long getCreated() {
      return created_;
    }

    public static final int STORE_HASH_CODE_FIELD_NUMBER = 5;
    private long storeHashCode_;
    /**
     * <code>int64 store_hash_code = 5;</code>
     */
    public long getStoreHashCode() {
      return storeHashCode_;
    }

    public static final int RATE_FIELD_NUMBER = 6;
    private long rate_;
    /**
     * <code>int64 rate = 6;</code>
     */
    public long getRate() {
      return rate_;
    }

    public static final int LIKE_FIELD_NUMBER = 7;
    private boolean like_;
    /**
     * <code>bool like = 7;</code>
     */
    public boolean getLike() {
      return like_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, description_);
      }
      if (hashCode_ != 0L) {
        output.writeInt64(2, hashCode_);
      }
      if (!getCreatorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, creator_);
      }
      if (created_ != 0L) {
        output.writeInt64(4, created_);
      }
      if (storeHashCode_ != 0L) {
        output.writeInt64(5, storeHashCode_);
      }
      if (rate_ != 0L) {
        output.writeInt64(6, rate_);
      }
      if (like_ != false) {
        output.writeBool(7, like_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, description_);
      }
      if (hashCode_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, hashCode_);
      }
      if (!getCreatorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, creator_);
      }
      if (created_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, created_);
      }
      if (storeHashCode_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, storeHashCode_);
      }
      if (rate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, rate_);
      }
      if (like_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, like_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ir.asparsa.common.net.dto.CommentProto.Comment)) {
        return super.equals(obj);
      }
      ir.asparsa.common.net.dto.CommentProto.Comment other = (ir.asparsa.common.net.dto.CommentProto.Comment) obj;

      boolean result = true;
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && (getHashCode()
          == other.getHashCode());
      result = result && getCreator()
          .equals(other.getCreator());
      result = result && (getCreated()
          == other.getCreated());
      result = result && (getStoreHashCode()
          == other.getStoreHashCode());
      result = result && (getRate()
          == other.getRate());
      result = result && (getLike()
          == other.getLike());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + HASH_CODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHashCode());
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
      hash = (37 * hash) + CREATED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreated());
      hash = (37 * hash) + STORE_HASH_CODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStoreHashCode());
      hash = (37 * hash) + RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRate());
      hash = (37 * hash) + LIKE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLike());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ir.asparsa.common.net.dto.CommentProto.Comment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.CommentProto.Comment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ir.asparsa.common.net.dto.CommentProto.Comment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ir.asparsa.common.net.dto.Comment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ir.asparsa.common.net.dto.Comment)
        ir.asparsa.common.net.dto.CommentProto.CommentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ir.asparsa.common.net.dto.CommentProto.Comment.class, ir.asparsa.common.net.dto.CommentProto.Comment.Builder.class);
      }

      // Construct using ir.asparsa.common.net.dto.CommentProto.Comment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        description_ = "";

        hashCode_ = 0L;

        creator_ = "";

        created_ = 0L;

        storeHashCode_ = 0L;

        rate_ = 0L;

        like_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ir.asparsa.common.net.dto.CommentProto.internal_static_ir_asparsa_common_net_dto_Comment_descriptor;
      }

      public ir.asparsa.common.net.dto.CommentProto.Comment getDefaultInstanceForType() {
        return ir.asparsa.common.net.dto.CommentProto.Comment.getDefaultInstance();
      }

      public ir.asparsa.common.net.dto.CommentProto.Comment build() {
        ir.asparsa.common.net.dto.CommentProto.Comment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ir.asparsa.common.net.dto.CommentProto.Comment buildPartial() {
        ir.asparsa.common.net.dto.CommentProto.Comment result = new ir.asparsa.common.net.dto.CommentProto.Comment(this);
        result.description_ = description_;
        result.hashCode_ = hashCode_;
        result.creator_ = creator_;
        result.created_ = created_;
        result.storeHashCode_ = storeHashCode_;
        result.rate_ = rate_;
        result.like_ = like_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ir.asparsa.common.net.dto.CommentProto.Comment) {
          return mergeFrom((ir.asparsa.common.net.dto.CommentProto.Comment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ir.asparsa.common.net.dto.CommentProto.Comment other) {
        if (other == ir.asparsa.common.net.dto.CommentProto.Comment.getDefaultInstance()) return this;
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getHashCode() != 0L) {
          setHashCode(other.getHashCode());
        }
        if (!other.getCreator().isEmpty()) {
          creator_ = other.creator_;
          onChanged();
        }
        if (other.getCreated() != 0L) {
          setCreated(other.getCreated());
        }
        if (other.getStoreHashCode() != 0L) {
          setStoreHashCode(other.getStoreHashCode());
        }
        if (other.getRate() != 0L) {
          setRate(other.getRate());
        }
        if (other.getLike() != false) {
          setLike(other.getLike());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ir.asparsa.common.net.dto.CommentProto.Comment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ir.asparsa.common.net.dto.CommentProto.Comment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 1;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 1;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 1;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 1;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private long hashCode_ ;
      /**
       * <code>int64 hash_code = 2;</code>
       */
      public long getHashCode() {
        return hashCode_;
      }
      /**
       * <code>int64 hash_code = 2;</code>
       */
      public Builder setHashCode(long value) {
        
        hashCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 hash_code = 2;</code>
       */
      public Builder clearHashCode() {
        
        hashCode_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object creator_ = "";
      /**
       * <code>string creator = 3;</code>
       */
      public java.lang.String getCreator() {
        java.lang.Object ref = creator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string creator = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        java.lang.Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string creator = 3;</code>
       */
      public Builder setCreator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        creator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string creator = 3;</code>
       */
      public Builder clearCreator() {
        
        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      /**
       * <code>string creator = 3;</code>
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        creator_ = value;
        onChanged();
        return this;
      }

      private long created_ ;
      /**
       * <code>int64 created = 4;</code>
       */
      public long getCreated() {
        return created_;
      }
      /**
       * <code>int64 created = 4;</code>
       */
      public Builder setCreated(long value) {
        
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 created = 4;</code>
       */
      public Builder clearCreated() {
        
        created_ = 0L;
        onChanged();
        return this;
      }

      private long storeHashCode_ ;
      /**
       * <code>int64 store_hash_code = 5;</code>
       */
      public long getStoreHashCode() {
        return storeHashCode_;
      }
      /**
       * <code>int64 store_hash_code = 5;</code>
       */
      public Builder setStoreHashCode(long value) {
        
        storeHashCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 store_hash_code = 5;</code>
       */
      public Builder clearStoreHashCode() {
        
        storeHashCode_ = 0L;
        onChanged();
        return this;
      }

      private long rate_ ;
      /**
       * <code>int64 rate = 6;</code>
       */
      public long getRate() {
        return rate_;
      }
      /**
       * <code>int64 rate = 6;</code>
       */
      public Builder setRate(long value) {
        
        rate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rate = 6;</code>
       */
      public Builder clearRate() {
        
        rate_ = 0L;
        onChanged();
        return this;
      }

      private boolean like_ ;
      /**
       * <code>bool like = 7;</code>
       */
      public boolean getLike() {
        return like_;
      }
      /**
       * <code>bool like = 7;</code>
       */
      public Builder setLike(boolean value) {
        
        like_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool like = 7;</code>
       */
      public Builder clearLike() {
        
        like_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ir.asparsa.common.net.dto.Comment)
    }

    // @@protoc_insertion_point(class_scope:ir.asparsa.common.net.dto.Comment)
    private static final ir.asparsa.common.net.dto.CommentProto.Comment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ir.asparsa.common.net.dto.CommentProto.Comment();
    }

    public static ir.asparsa.common.net.dto.CommentProto.Comment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Comment>
        PARSER = new com.google.protobuf.AbstractParser<Comment>() {
      public Comment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Comment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Comment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Comment> getParserForType() {
      return PARSER;
    }

    public ir.asparsa.common.net.dto.CommentProto.Comment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ir_asparsa_common_net_dto_Comments_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ir_asparsa_common_net_dto_Comments_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ir_asparsa_common_net_dto_Comment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ir_asparsa_common_net_dto_Comment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcomment.proto\022\031ir.asparsa.common.net.d" +
      "to\"V\n\010Comments\0223\n\007comment\030\001 \003(\0132\".ir.asp" +
      "arsa.common.net.dto.Comment\022\025\n\rtotalElem" +
      "ents\030\002 \001(\003\"\210\001\n\007Comment\022\023\n\013description\030\001 " +
      "\001(\t\022\021\n\thash_code\030\002 \001(\003\022\017\n\007creator\030\003 \001(\t\022" +
      "\017\n\007created\030\004 \001(\003\022\027\n\017store_hash_code\030\005 \001(" +
      "\003\022\014\n\004rate\030\006 \001(\003\022\014\n\004like\030\007 \001(\010B\016B\014Comment" +
      "Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ir_asparsa_common_net_dto_Comments_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ir_asparsa_common_net_dto_Comments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ir_asparsa_common_net_dto_Comments_descriptor,
        new java.lang.String[] { "Comment", "TotalElements", });
    internal_static_ir_asparsa_common_net_dto_Comment_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ir_asparsa_common_net_dto_Comment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ir_asparsa_common_net_dto_Comment_descriptor,
        new java.lang.String[] { "Description", "HashCode", "Creator", "Created", "StoreHashCode", "Rate", "Like", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
