// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feedback.proto

package ir.asparsa.common.net.dto;

public final class FeedbackProto {
  private FeedbackProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FeedbackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ir.asparsa.common.net.dto.Feedback)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string body = 1;</code>
     */
    java.lang.String getBody();
    /**
     * <code>string body = 1;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>string crash_throwable_name = 2;</code>
     */
    java.lang.String getCrashThrowableName();
    /**
     * <code>string crash_throwable_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getCrashThrowableNameBytes();

    /**
     * <code>string crash_message = 3;</code>
     */
    java.lang.String getCrashMessage();
    /**
     * <code>string crash_message = 3;</code>
     */
    com.google.protobuf.ByteString
        getCrashMessageBytes();
  }
  /**
   * Protobuf type {@code ir.asparsa.common.net.dto.Feedback}
   */
  public  static final class Feedback extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ir.asparsa.common.net.dto.Feedback)
      FeedbackOrBuilder {
    // Use Feedback.newBuilder() to construct.
    private Feedback(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Feedback() {
      body_ = "";
      crashThrowableName_ = "";
      crashMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Feedback(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              crashThrowableName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              crashMessage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.asparsa.common.net.dto.FeedbackProto.internal_static_ir_asparsa_common_net_dto_Feedback_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.asparsa.common.net.dto.FeedbackProto.internal_static_ir_asparsa_common_net_dto_Feedback_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.asparsa.common.net.dto.FeedbackProto.Feedback.class, ir.asparsa.common.net.dto.FeedbackProto.Feedback.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 1;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CRASH_THROWABLE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object crashThrowableName_;
    /**
     * <code>string crash_throwable_name = 2;</code>
     */
    public java.lang.String getCrashThrowableName() {
      java.lang.Object ref = crashThrowableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        crashThrowableName_ = s;
        return s;
      }
    }
    /**
     * <code>string crash_throwable_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCrashThrowableNameBytes() {
      java.lang.Object ref = crashThrowableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        crashThrowableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CRASH_MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object crashMessage_;
    /**
     * <code>string crash_message = 3;</code>
     */
    public java.lang.String getCrashMessage() {
      java.lang.Object ref = crashMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        crashMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string crash_message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCrashMessageBytes() {
      java.lang.Object ref = crashMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        crashMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, body_);
      }
      if (!getCrashThrowableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, crashThrowableName_);
      }
      if (!getCrashMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, crashMessage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, body_);
      }
      if (!getCrashThrowableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, crashThrowableName_);
      }
      if (!getCrashMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, crashMessage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ir.asparsa.common.net.dto.FeedbackProto.Feedback)) {
        return super.equals(obj);
      }
      ir.asparsa.common.net.dto.FeedbackProto.Feedback other = (ir.asparsa.common.net.dto.FeedbackProto.Feedback) obj;

      boolean result = true;
      result = result && getBody()
          .equals(other.getBody());
      result = result && getCrashThrowableName()
          .equals(other.getCrashThrowableName());
      result = result && getCrashMessage()
          .equals(other.getCrashMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + CRASH_THROWABLE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCrashThrowableName().hashCode();
      hash = (37 * hash) + CRASH_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getCrashMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ir.asparsa.common.net.dto.FeedbackProto.Feedback prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ir.asparsa.common.net.dto.Feedback}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ir.asparsa.common.net.dto.Feedback)
        ir.asparsa.common.net.dto.FeedbackProto.FeedbackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ir.asparsa.common.net.dto.FeedbackProto.internal_static_ir_asparsa_common_net_dto_Feedback_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ir.asparsa.common.net.dto.FeedbackProto.internal_static_ir_asparsa_common_net_dto_Feedback_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ir.asparsa.common.net.dto.FeedbackProto.Feedback.class, ir.asparsa.common.net.dto.FeedbackProto.Feedback.Builder.class);
      }

      // Construct using ir.asparsa.common.net.dto.FeedbackProto.Feedback.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        body_ = "";

        crashThrowableName_ = "";

        crashMessage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ir.asparsa.common.net.dto.FeedbackProto.internal_static_ir_asparsa_common_net_dto_Feedback_descriptor;
      }

      public ir.asparsa.common.net.dto.FeedbackProto.Feedback getDefaultInstanceForType() {
        return ir.asparsa.common.net.dto.FeedbackProto.Feedback.getDefaultInstance();
      }

      public ir.asparsa.common.net.dto.FeedbackProto.Feedback build() {
        ir.asparsa.common.net.dto.FeedbackProto.Feedback result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ir.asparsa.common.net.dto.FeedbackProto.Feedback buildPartial() {
        ir.asparsa.common.net.dto.FeedbackProto.Feedback result = new ir.asparsa.common.net.dto.FeedbackProto.Feedback(this);
        result.body_ = body_;
        result.crashThrowableName_ = crashThrowableName_;
        result.crashMessage_ = crashMessage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ir.asparsa.common.net.dto.FeedbackProto.Feedback) {
          return mergeFrom((ir.asparsa.common.net.dto.FeedbackProto.Feedback)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ir.asparsa.common.net.dto.FeedbackProto.Feedback other) {
        if (other == ir.asparsa.common.net.dto.FeedbackProto.Feedback.getDefaultInstance()) return this;
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (!other.getCrashThrowableName().isEmpty()) {
          crashThrowableName_ = other.crashThrowableName_;
          onChanged();
        }
        if (!other.getCrashMessage().isEmpty()) {
          crashMessage_ = other.crashMessage_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ir.asparsa.common.net.dto.FeedbackProto.Feedback parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ir.asparsa.common.net.dto.FeedbackProto.Feedback) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 1;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 1;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 1;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 1;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object crashThrowableName_ = "";
      /**
       * <code>string crash_throwable_name = 2;</code>
       */
      public java.lang.String getCrashThrowableName() {
        java.lang.Object ref = crashThrowableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          crashThrowableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string crash_throwable_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCrashThrowableNameBytes() {
        java.lang.Object ref = crashThrowableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          crashThrowableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string crash_throwable_name = 2;</code>
       */
      public Builder setCrashThrowableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        crashThrowableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string crash_throwable_name = 2;</code>
       */
      public Builder clearCrashThrowableName() {
        
        crashThrowableName_ = getDefaultInstance().getCrashThrowableName();
        onChanged();
        return this;
      }
      /**
       * <code>string crash_throwable_name = 2;</code>
       */
      public Builder setCrashThrowableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        crashThrowableName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object crashMessage_ = "";
      /**
       * <code>string crash_message = 3;</code>
       */
      public java.lang.String getCrashMessage() {
        java.lang.Object ref = crashMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          crashMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string crash_message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCrashMessageBytes() {
        java.lang.Object ref = crashMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          crashMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string crash_message = 3;</code>
       */
      public Builder setCrashMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        crashMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string crash_message = 3;</code>
       */
      public Builder clearCrashMessage() {
        
        crashMessage_ = getDefaultInstance().getCrashMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string crash_message = 3;</code>
       */
      public Builder setCrashMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        crashMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ir.asparsa.common.net.dto.Feedback)
    }

    // @@protoc_insertion_point(class_scope:ir.asparsa.common.net.dto.Feedback)
    private static final ir.asparsa.common.net.dto.FeedbackProto.Feedback DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ir.asparsa.common.net.dto.FeedbackProto.Feedback();
    }

    public static ir.asparsa.common.net.dto.FeedbackProto.Feedback getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Feedback>
        PARSER = new com.google.protobuf.AbstractParser<Feedback>() {
      public Feedback parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Feedback(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Feedback> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Feedback> getParserForType() {
      return PARSER;
    }

    public ir.asparsa.common.net.dto.FeedbackProto.Feedback getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ir_asparsa_common_net_dto_Feedback_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ir_asparsa_common_net_dto_Feedback_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016feedback.proto\022\031ir.asparsa.common.net." +
      "dto\"M\n\010Feedback\022\014\n\004body\030\001 \001(\t\022\034\n\024crash_t" +
      "hrowable_name\030\002 \001(\t\022\025\n\rcrash_message\030\003 \001" +
      "(\tB\017B\rFeedbackProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ir_asparsa_common_net_dto_Feedback_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ir_asparsa_common_net_dto_Feedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ir_asparsa_common_net_dto_Feedback_descriptor,
        new java.lang.String[] { "Body", "CrashThrowableName", "CrashMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
