// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package ir.asparsa.common.net.dto;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ir.asparsa.common.net.dto.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ir.asparsa.common.net.dto.Response.StatusType status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.ir.asparsa.common.net.dto.Response.StatusType status = 1;</code>
     */
    ir.asparsa.common.net.dto.ResponseProto.Response.StatusType getStatus();

    /**
     * <code>string detail_message = 2;</code>
     */
    java.lang.String getDetailMessage();
    /**
     * <code>string detail_message = 2;</code>
     */
    com.google.protobuf.ByteString
        getDetailMessageBytes();

    /**
     * <code>string localized_message = 3;</code>
     */
    java.lang.String getLocalizedMessage();
    /**
     * <code>string localized_message = 3;</code>
     */
    com.google.protobuf.ByteString
        getLocalizedMessageBytes();
  }
  /**
   * Protobuf type {@code ir.asparsa.common.net.dto.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ir.asparsa.common.net.dto.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      status_ = 0;
      detailMessage_ = "";
      localizedMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              detailMessage_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              localizedMessage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.asparsa.common.net.dto.ResponseProto.internal_static_ir_asparsa_common_net_dto_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.asparsa.common.net.dto.ResponseProto.internal_static_ir_asparsa_common_net_dto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.asparsa.common.net.dto.ResponseProto.Response.class, ir.asparsa.common.net.dto.ResponseProto.Response.Builder.class);
    }

    /**
     * Protobuf enum {@code ir.asparsa.common.net.dto.Response.StatusType}
     */
    public enum StatusType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCEED = 0;</code>
       */
      SUCCEED(0),
      /**
       * <code>ERROR = 1;</code>
       */
      ERROR(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SUCCEED = 0;</code>
       */
      public static final int SUCCEED_VALUE = 0;
      /**
       * <code>ERROR = 1;</code>
       */
      public static final int ERROR_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static StatusType valueOf(int value) {
        return forNumber(value);
      }

      public static StatusType forNumber(int value) {
        switch (value) {
          case 0: return SUCCEED;
          case 1: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          StatusType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusType>() {
              public StatusType findValueByNumber(int number) {
                return StatusType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ir.asparsa.common.net.dto.ResponseProto.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final StatusType[] VALUES = values();

      public static StatusType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private StatusType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ir.asparsa.common.net.dto.Response.StatusType)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.ir.asparsa.common.net.dto.Response.StatusType status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.ir.asparsa.common.net.dto.Response.StatusType status = 1;</code>
     */
    public ir.asparsa.common.net.dto.ResponseProto.Response.StatusType getStatus() {
      ir.asparsa.common.net.dto.ResponseProto.Response.StatusType result = ir.asparsa.common.net.dto.ResponseProto.Response.StatusType.valueOf(status_);
      return result == null ? ir.asparsa.common.net.dto.ResponseProto.Response.StatusType.UNRECOGNIZED : result;
    }

    public static final int DETAIL_MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object detailMessage_;
    /**
     * <code>string detail_message = 2;</code>
     */
    public java.lang.String getDetailMessage() {
      java.lang.Object ref = detailMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detailMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string detail_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDetailMessageBytes() {
      java.lang.Object ref = detailMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detailMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALIZED_MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object localizedMessage_;
    /**
     * <code>string localized_message = 3;</code>
     */
    public java.lang.String getLocalizedMessage() {
      java.lang.Object ref = localizedMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localizedMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string localized_message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocalizedMessageBytes() {
      java.lang.Object ref = localizedMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localizedMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != ir.asparsa.common.net.dto.ResponseProto.Response.StatusType.SUCCEED.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (!getDetailMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, detailMessage_);
      }
      if (!getLocalizedMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, localizedMessage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != ir.asparsa.common.net.dto.ResponseProto.Response.StatusType.SUCCEED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (!getDetailMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, detailMessage_);
      }
      if (!getLocalizedMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, localizedMessage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ir.asparsa.common.net.dto.ResponseProto.Response)) {
        return super.equals(obj);
      }
      ir.asparsa.common.net.dto.ResponseProto.Response other = (ir.asparsa.common.net.dto.ResponseProto.Response) obj;

      boolean result = true;
      result = result && status_ == other.status_;
      result = result && getDetailMessage()
          .equals(other.getDetailMessage());
      result = result && getLocalizedMessage()
          .equals(other.getLocalizedMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + DETAIL_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getDetailMessage().hashCode();
      hash = (37 * hash) + LOCALIZED_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLocalizedMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ir.asparsa.common.net.dto.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.asparsa.common.net.dto.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.ResponseProto.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.asparsa.common.net.dto.ResponseProto.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.ResponseProto.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.ResponseProto.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.ResponseProto.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.ResponseProto.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.asparsa.common.net.dto.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.asparsa.common.net.dto.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ir.asparsa.common.net.dto.ResponseProto.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ir.asparsa.common.net.dto.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ir.asparsa.common.net.dto.Response)
        ir.asparsa.common.net.dto.ResponseProto.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ir.asparsa.common.net.dto.ResponseProto.internal_static_ir_asparsa_common_net_dto_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ir.asparsa.common.net.dto.ResponseProto.internal_static_ir_asparsa_common_net_dto_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ir.asparsa.common.net.dto.ResponseProto.Response.class, ir.asparsa.common.net.dto.ResponseProto.Response.Builder.class);
      }

      // Construct using ir.asparsa.common.net.dto.ResponseProto.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        detailMessage_ = "";

        localizedMessage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ir.asparsa.common.net.dto.ResponseProto.internal_static_ir_asparsa_common_net_dto_Response_descriptor;
      }

      public ir.asparsa.common.net.dto.ResponseProto.Response getDefaultInstanceForType() {
        return ir.asparsa.common.net.dto.ResponseProto.Response.getDefaultInstance();
      }

      public ir.asparsa.common.net.dto.ResponseProto.Response build() {
        ir.asparsa.common.net.dto.ResponseProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ir.asparsa.common.net.dto.ResponseProto.Response buildPartial() {
        ir.asparsa.common.net.dto.ResponseProto.Response result = new ir.asparsa.common.net.dto.ResponseProto.Response(this);
        result.status_ = status_;
        result.detailMessage_ = detailMessage_;
        result.localizedMessage_ = localizedMessage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ir.asparsa.common.net.dto.ResponseProto.Response) {
          return mergeFrom((ir.asparsa.common.net.dto.ResponseProto.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ir.asparsa.common.net.dto.ResponseProto.Response other) {
        if (other == ir.asparsa.common.net.dto.ResponseProto.Response.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getDetailMessage().isEmpty()) {
          detailMessage_ = other.detailMessage_;
          onChanged();
        }
        if (!other.getLocalizedMessage().isEmpty()) {
          localizedMessage_ = other.localizedMessage_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ir.asparsa.common.net.dto.ResponseProto.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ir.asparsa.common.net.dto.ResponseProto.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.ir.asparsa.common.net.dto.Response.StatusType status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.ir.asparsa.common.net.dto.Response.StatusType status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ir.asparsa.common.net.dto.Response.StatusType status = 1;</code>
       */
      public ir.asparsa.common.net.dto.ResponseProto.Response.StatusType getStatus() {
        ir.asparsa.common.net.dto.ResponseProto.Response.StatusType result = ir.asparsa.common.net.dto.ResponseProto.Response.StatusType.valueOf(status_);
        return result == null ? ir.asparsa.common.net.dto.ResponseProto.Response.StatusType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ir.asparsa.common.net.dto.Response.StatusType status = 1;</code>
       */
      public Builder setStatus(ir.asparsa.common.net.dto.ResponseProto.Response.StatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ir.asparsa.common.net.dto.Response.StatusType status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object detailMessage_ = "";
      /**
       * <code>string detail_message = 2;</code>
       */
      public java.lang.String getDetailMessage() {
        java.lang.Object ref = detailMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          detailMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string detail_message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDetailMessageBytes() {
        java.lang.Object ref = detailMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          detailMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string detail_message = 2;</code>
       */
      public Builder setDetailMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        detailMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string detail_message = 2;</code>
       */
      public Builder clearDetailMessage() {
        
        detailMessage_ = getDefaultInstance().getDetailMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string detail_message = 2;</code>
       */
      public Builder setDetailMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        detailMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object localizedMessage_ = "";
      /**
       * <code>string localized_message = 3;</code>
       */
      public java.lang.String getLocalizedMessage() {
        java.lang.Object ref = localizedMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          localizedMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string localized_message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLocalizedMessageBytes() {
        java.lang.Object ref = localizedMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localizedMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string localized_message = 3;</code>
       */
      public Builder setLocalizedMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        localizedMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string localized_message = 3;</code>
       */
      public Builder clearLocalizedMessage() {
        
        localizedMessage_ = getDefaultInstance().getLocalizedMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string localized_message = 3;</code>
       */
      public Builder setLocalizedMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        localizedMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ir.asparsa.common.net.dto.Response)
    }

    // @@protoc_insertion_point(class_scope:ir.asparsa.common.net.dto.Response)
    private static final ir.asparsa.common.net.dto.ResponseProto.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ir.asparsa.common.net.dto.ResponseProto.Response();
    }

    public static ir.asparsa.common.net.dto.ResponseProto.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public ir.asparsa.common.net.dto.ResponseProto.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ir_asparsa_common_net_dto_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ir_asparsa_common_net_dto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\022\031ir.asparsa.common.net." +
      "dto\"\243\001\n\010Response\022>\n\006status\030\001 \001(\0162..ir.as" +
      "parsa.common.net.dto.Response.StatusType" +
      "\022\026\n\016detail_message\030\002 \001(\t\022\031\n\021localized_me" +
      "ssage\030\003 \001(\t\"$\n\nStatusType\022\013\n\007SUCCEED\020\000\022\t" +
      "\n\005ERROR\020\001B\017B\rResponseProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ir_asparsa_common_net_dto_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ir_asparsa_common_net_dto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ir_asparsa_common_net_dto_Response_descriptor,
        new java.lang.String[] { "Status", "DetailMessage", "LocalizedMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
